# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: typelib 0.1.1 ruby lib

Gem::Specification.new do |s|
  s.name = "typelib".freeze
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Erik Hollensbe".freeze]
  s.date = "2023-06-05"
  s.email = "erik@hollensbe.org".freeze
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/typelib.rb",
    "lib/typelib/canned.rb",
    "test/test_01_basic.rb",
    "test/test_02_canned.rb",
    "typelib.gemspec"
  ]
  s.homepage = "http://github.com/RDBI/typelib".freeze
  s.rubygems_version = "3.3.7".freeze
  s.summary = "An on-demand arbitrary check and conversion library that won't destroy your data.".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4
  end

  if s.respond_to? :add_runtime_dependency then
    s.add_development_dependency(%q<test-unit>.freeze, [">= 0"])
    s.add_development_dependency(%q<rdoc>.freeze, [">= 0"])
  else
    s.add_dependency(%q<test-unit>.freeze, [">= 0"])
    s.add_dependency(%q<rdoc>.freeze, [">= 0"])
  end
end

